name: Auto Update

on:
  push:
    branches: [ main ]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.7.0
      with:
         repository: ${{ github.repository }}
    - name: Copy file
      uses: canastro/copy-action@0.0.2
      with:
        source: dataupdate.ini
        target: update.ini
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4.16.0
      with:
        commit_message: Update update.ini
        commit_options: '--no-verify'
        file_pattern: update.ini
